
version: "2"

services:

# #####################################################
# Base services
  base_integration:
    mem_limit: 2g
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile.assemble

  base_volume:
    mem_limit: 1g
    image: ubuntu
    entrypoint: /bin/true

# #####################################################
# Integration services
  assembler:
    extends:
      service: base_integration
    command: /os/bin/assemble.sh
    depends_on:
      - source
      - target
    volumes_from:
      - source
      - target
    environment:
      - OS_TARGET=${OS_TARGET}
      - OS_APP=${OS_APP}
      - OS_BUILD=${OS_BUILD}

  watcher:
    extends:
      service: base_integration
    command: /os/bin/start.sh
    hostname: prodoo
    depends_on:
      - source
      - target
    volumes_from:
      - source
      - target
    ports:
      - 8000:8000
    environment:
      - OS_TARGET=${OS_TARGET}
      - OS_APP=${OS_APP}
      - OS_BUILD=${OS_BUILD}

  packager:
    extends:
      service: base_integration
    command: /os/bin/package.sh
    depends_on:
      - target
    volumes_from:
      - target
    environment:
      - OS_TARGET=${OS_TARGET}
      - OS_PUBLISH=${OS_PUBLISH}

  tester:
    extends:
      service: base_integration
    command: /os/bin/test.sh
    depends_on:
      - source
      - target
    volumes_from:
      - source
      - target
    environment:
      - OS_TARGET=${OS_TARGET}
      - OS_APP=${OS_APP}
      - OS_BUILD=${OS_BUILD}

  cleaner:
    extends:
      service: base_integration
    command: /os/bin/clean.sh
    depends_on:
      - source
      - target
    volumes_from:
      - source
      - target
    environment:
      - OS_TARGET=${OS_TARGET}
      - OS_APP=${OS_APP}
      - OS_BUILD=${OS_BUILD}

# #####################################################
# Volume services
  source:
    extends:
      service: base_volume
    volumes:
      -  ../../src:/os/build/src
      -  ../../etc:/os/build/etc
      -  ../../test:/os/build/test

  target:
    extends:
      service: base_volume
    volumes:
      -  ../../dist:/os/target
      -  ../../publish:/os/publish
